# Generated by Django 3.2.6 on 2021-08-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(choices=[('de', 'DE'), ('ch', 'CH')], max_length=2)),
                ('customer', models.CharField(choices=[('de', 'DE'), ('ch', 'CH'), ('fr', 'FR'), ('us', 'US')], max_length=2)),
                ('net', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=4)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classification', models.CharField(max_length=2)),
            ],
        ),
    ]
