# Generated by Django 3.2.6 on 2021-08-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffcalc',
            name='classification',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='tariffcalc',
            name='gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tariffcalc',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4),
        ),
    ]
