# Generated by Django 3.2.6 on 2021-08-09 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clickapp", "0002_auto_20210808_2302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariffcalc",
            name="net",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
