# Generated by Django 3.2.6 on 2021-08-09 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clickapp", "0003_alter_tariffcalc_net"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariffcalc",
            name="gross",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="tariffcalc",
            name="net",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=11,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
